name: middleware_dart
description: A platform for creating middleware inspired by middleware-io. It has many snippets and has no dependencies.
version: 1.0.0
repository: https://github.com/swedesjs/middleware_dart

environment:
  sdk: ^3.2.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
